# Generated by Django 3.0.7 on 2020-06-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200629_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creator',
            new_name='user',
        ),
    ]
